### PR TITLE
Various fixes (keyboard navigation)

### LINKED ISSUE #608: Selected text slot isn't removed when using "del" key
I've triple-clicked a text slot to select the text. Then hit the "del" key, but the deletion didn't happen (however, the selection disappeared).
(Seems this needs to be when we are in a new project.)

### PR DESCRIPTION
**Pull request by PwtKCL**
This PR mainly addresses some issues/new features about the keyboard navigation in the editor.

There is an issue with macOS: home/end are not dedicated key and the equivalent is ⌘ + left/right.
In the following we will mention "home" and "end" **as the _functional_ role**: that means the keys are indeed home and end _for windows only_ but ⌘ + left and or ⌘ + right _for macOS_.

To summarise:
- only home/end is handled by the browser for comments (as it was before), string literals (#607) and documentation slots (both new behaviour) -- ,
- home/end *without selection* now moves to the start/end of the whole label slots structure for other cases, instead of moving to the current structural level
- home/send *with selection* behaves as before (that is it will go to the start/end of the current structural level)
- home/end keeps the same behaviour for the frame cursor (going to the top/end of the current frames section),  but now if ctrl is hold together, we reach the very top/end of the whole editor (that not collapsed)
- page up/page down now acts as up/down when within a text slot (of any kind); "scrolls" up/down the frame cursor when the frame cursor is showing

For Chrome, this PR also contains a fix for the triple click slot content selection (#611 which fixes #608 and #609).
**Note that at the moment, for Firefox at least, the triple click doesn't work at all - this is mentioned in a separate issue.**

Finally, the format of the label slots' id has been slightly modified to use greater SlotType values, notably so that it properly reflects the SlotType values for comments (i.e. documentation slots) and media.

### CODE REVIEW

File: src/components/LabelSlot.vue [hunk 1]
```diff
@@ -1129,40 +1131,65 @@ export default Vue.extend({
...
 
         handleFastUDNavKeys(event: KeyboardEvent){
-            // If we are in a comment, we let the browser handling the key events.
+            // If we are in a comment (e.g. frame or documentation slot) or in a string slot, we let the browser* handling the key events.
             // Otherwise, the following rules apply:
-            // Home/End move the text cursor to the start/end of the "block" unit of the code, for example the start of a slot bracketed structure
-            // PageUp/PageDown: do nothing
-            if(this.frameType == AllFrameTypesIdentifier.comment){
+            // Home/End* move the text cursor to the start/end of the whole label slots structure, or of the current slot structure level
+            //      (like a bracketed structure) if shit is also held (to avoid selecting code that spans across different levels)
```
Comment (neilccbrown) [inline src/components/LabelSlot.vue]: Small typo...

File: src/components/LabelSlot.vue [hunk 2]
```diff
@@ -1129,40 +1131,65 @@ export default Vue.extend({
...
                     setDocumentSelection(newAnchorSlotCursorInfo, {slotInfos: newFocusSlotCoreInfo, cursorPos: newFocusCursorPos});
                     this.appStore.setSlotTextCursors(newAnchorSlotCursorInfo, {slotInfos: newFocusSlotCoreInfo, cursorPos: newFocusCursorPos});
+
                 });
                 event.preventDefault();
                 event.stopPropagation();
                 event.stopImmediatePropagation();
             }
+            else{
+                // The case of PageUp and PageDown
```
Comment (neilccbrown) [inline src/components/LabelSlot.vue]: Maybe just mention again here: this leaves the slot to a frame cursor.
